/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package prime.kotlin

const val UpTo = 200000u;

fun main(args: Array<String>) {

    var numberOfThreads = 1u;

    if (args.size > 0) {
        numberOfThreads = args[0].toUInt();
    }

    println("Run with $numberOfThreads threads up to $UpTo");
    val count = countPrimes(UpTo, numberOfThreads);
    println("Found $count prime numbers up to $UpTo");
}
