name: Rust

on:
  push:
    branches: [ "main", "atomic" ]
  pull_request:
    branches: [ "main", "atomic" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      working-directory: ./prime-rust
      run: cargo build --verbose
    - name: Run tests
      working-directory: ./prime-rust
      run: cargo test --verbose
